# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Jun 14 12:39:39 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 623)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_TCP = QtGui.QWidget()
        self.tab_TCP.setObjectName("tab_TCP")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_TCP)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_4 = QtGui.QGroupBox(self.tab_TCP)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("TCPlost.png"))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.gridLayout_5.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_TCP)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textEdit = QtGui.QTextEdit(self.groupBox_3)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_TCP)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.TCPloss_Step1 = QtGui.QPushButton(self.groupBox_2)
        self.TCPloss_Step1.setObjectName("TCPloss_Step1")
        self.gridLayout.addWidget(self.TCPloss_Step1, 0, 1, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.lineEdit.setFont(font)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.TCPloss_Exit = QtGui.QPushButton(self.groupBox_2)
        self.TCPloss_Exit.setObjectName("TCPloss_Exit")
        self.gridLayout.addWidget(self.TCPloss_Exit, 4, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.TCPloss_Step2 = QtGui.QPushButton(self.groupBox_2)
        self.TCPloss_Step2.setObjectName("TCPloss_Step2")
        self.gridLayout.addWidget(self.TCPloss_Step2, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 2, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(self.tab_TCP)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.TCPloss_delay = QtGui.QSpinBox(self.groupBox)
        self.TCPloss_delay.setSuffix("")
        self.TCPloss_delay.setMaximum(5000)
        self.TCPloss_delay.setSingleStep(10)
        self.TCPloss_delay.setProperty("value", 20)
        self.TCPloss_delay.setObjectName("TCPloss_delay")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.TCPloss_delay)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.TCPloss_loss = QtGui.QSpinBox(self.groupBox)
        self.TCPloss_loss.setSuffix("")
        self.TCPloss_loss.setPrefix("")
        self.TCPloss_loss.setMaximum(100)
        self.TCPloss_loss.setProperty("value", 5)
        self.TCPloss_loss.setObjectName("TCPloss_loss")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.TCPloss_loss)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.TCPloss_swin = QtGui.QSpinBox(self.groupBox)
        self.TCPloss_swin.setMinimum(1)
        self.TCPloss_swin.setProperty("value", 3)
        self.TCPloss_swin.setObjectName("TCPloss_swin")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.TCPloss_swin)
        self.gridLayout_5.addWidget(self.groupBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_TCP, "")
        self.tab_DHCP = QtGui.QWidget()
        self.tab_DHCP.setObjectName("tab_DHCP")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_DHCP)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_5 = QtGui.QGroupBox(self.tab_DHCP)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit_2 = QtGui.QTextEdit(self.groupBox_5)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_3.addWidget(self.textEdit_2)
        self.gridLayout_4.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_DHCP)
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_7)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.DHCP_delay = QtGui.QSpinBox(self.groupBox_7)
        self.DHCP_delay.setSuffix("")
        self.DHCP_delay.setMaximum(5000)
        self.DHCP_delay.setSingleStep(10)
        self.DHCP_delay.setProperty("value", 20)
        self.DHCP_delay.setObjectName("DHCP_delay")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.DHCP_delay)
        self.DHCP_daemon_leases = QtGui.QCheckBox(self.groupBox_7)
        self.DHCP_daemon_leases.setChecked(True)
        self.DHCP_daemon_leases.setTristate(False)
        self.DHCP_daemon_leases.setObjectName("DHCP_daemon_leases")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.SpanningRole, self.DHCP_daemon_leases)
        self.DHCP_client_leases = QtGui.QCheckBox(self.groupBox_7)
        self.DHCP_client_leases.setChecked(True)
        self.DHCP_client_leases.setObjectName("DHCP_client_leases")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.SpanningRole, self.DHCP_client_leases)
        self.DHCP_random_MAC = QtGui.QCheckBox(self.groupBox_7)
        self.DHCP_random_MAC.setChecked(False)
        self.DHCP_random_MAC.setObjectName("DHCP_random_MAC")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.SpanningRole, self.DHCP_random_MAC)
        self.gridLayout_4.addWidget(self.groupBox_7, 1, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_DHCP)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtGui.QLabel(self.groupBox_6)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("TCPlost.png"))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.gridLayout_4.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_DHCP)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtGui.QLabel(self.groupBox_8)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.DHCP_Step1 = QtGui.QPushButton(self.groupBox_8)
        self.DHCP_Step1.setObjectName("DHCP_Step1")
        self.gridLayout_2.addWidget(self.DHCP_Step1, 0, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_8)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 3, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_8)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 4, 0, 1, 1)
        self.DHCP_Exit = QtGui.QPushButton(self.groupBox_8)
        self.DHCP_Exit.setObjectName("DHCP_Exit")
        self.gridLayout_2.addWidget(self.DHCP_Exit, 4, 1, 1, 1)
        self.DHCP_Step2 = QtGui.QPushButton(self.groupBox_8)
        self.DHCP_Step2.setObjectName("DHCP_Step2")
        self.gridLayout_2.addWidget(self.DHCP_Step2, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_8)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_8)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_8, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_DHCP, "")
        self.tab_FTP = QtGui.QWidget()
        self.tab_FTP.setObjectName("tab_FTP")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_FTP)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_10 = QtGui.QGroupBox(self.tab_FTP)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_13 = QtGui.QLabel(self.groupBox_10)
        self.label_13.setMinimumSize(QtCore.QSize(0, 0))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("TCPlost.png"))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_7.addWidget(self.label_13)
        self.gridLayout_3.addWidget(self.groupBox_10, 0, 1, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_FTP)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textEdit_3 = QtGui.QTextEdit(self.groupBox_9)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_5.addWidget(self.textEdit_3)
        self.gridLayout_3.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.groupBox_13 = QtGui.QGroupBox(self.tab_FTP)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_13)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_18 = QtGui.QLabel(self.groupBox_13)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 0, 1, 1)
        self.FTP_Step1 = QtGui.QPushButton(self.groupBox_13)
        self.FTP_Step1.setObjectName("FTP_Step1")
        self.gridLayout_6.addWidget(self.FTP_Step1, 0, 1, 1, 1)
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_13)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_6.addWidget(self.lineEdit_3, 3, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_13)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 4, 0, 1, 1)
        self.FTP_Exit = QtGui.QPushButton(self.groupBox_13)
        self.FTP_Exit.setObjectName("FTP_Exit")
        self.gridLayout_6.addWidget(self.FTP_Exit, 4, 1, 1, 1)
        self.FTP_Step2 = QtGui.QPushButton(self.groupBox_13)
        self.FTP_Step2.setObjectName("FTP_Step2")
        self.gridLayout_6.addWidget(self.FTP_Step2, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_13)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_13)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_13, 2, 0, 1, 2)
        self.groupBox_12 = QtGui.QGroupBox(self.tab_FTP)
        self.groupBox_12.setObjectName("groupBox_12")
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_12)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_16 = QtGui.QLabel(self.groupBox_12)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_16)
        self.FTP_delay = QtGui.QSpinBox(self.groupBox_12)
        self.FTP_delay.setSuffix("")
        self.FTP_delay.setMaximum(5000)
        self.FTP_delay.setSingleStep(10)
        self.FTP_delay.setProperty("value", 20)
        self.FTP_delay.setObjectName("FTP_delay")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.FTP_delay)
        self.FTP_pasv = QtGui.QCheckBox(self.groupBox_12)
        self.FTP_pasv.setChecked(True)
        self.FTP_pasv.setTristate(False)
        self.FTP_pasv.setObjectName("FTP_pasv")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.SpanningRole, self.FTP_pasv)
        self.gridLayout_3.addWidget(self.groupBox_12, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_FTP, "")
        self.tab_VoIP = QtGui.QWidget()
        self.tab_VoIP.setObjectName("tab_VoIP")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_VoIP)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_11 = QtGui.QGroupBox(self.tab_VoIP)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.textEdit_4 = QtGui.QTextEdit(self.groupBox_11)
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_8.addWidget(self.textEdit_4)
        self.gridLayout_8.addWidget(self.groupBox_11, 1, 0, 1, 1)
        self.groupBox_14 = QtGui.QGroupBox(self.tab_VoIP)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_15 = QtGui.QLabel(self.groupBox_14)
        self.label_15.setMinimumSize(QtCore.QSize(0, 0))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("TCPlost.png"))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_9.addWidget(self.label_15)
        self.gridLayout_8.addWidget(self.groupBox_14, 1, 1, 1, 1)
        self.groupBox_16 = QtGui.QGroupBox(self.tab_VoIP)
        self.groupBox_16.setObjectName("groupBox_16")
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_16)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_24 = QtGui.QLabel(self.groupBox_16)
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setObjectName("label_24")
        self.gridLayout_11.addWidget(self.label_24, 0, 0, 1, 1)
        self.VoIP_Step1 = QtGui.QPushButton(self.groupBox_16)
        self.VoIP_Step1.setObjectName("VoIP_Step1")
        self.gridLayout_11.addWidget(self.VoIP_Step1, 0, 1, 1, 1)
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_16)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_11.addWidget(self.lineEdit_4, 3, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_16)
        self.label_25.setObjectName("label_25")
        self.gridLayout_11.addWidget(self.label_25, 4, 0, 1, 1)
        self.VoIP_Exit = QtGui.QPushButton(self.groupBox_16)
        self.VoIP_Exit.setObjectName("VoIP_Exit")
        self.gridLayout_11.addWidget(self.VoIP_Exit, 4, 1, 1, 1)
        self.VoIP_Step2 = QtGui.QPushButton(self.groupBox_16)
        self.VoIP_Step2.setObjectName("VoIP_Step2")
        self.gridLayout_11.addWidget(self.VoIP_Step2, 1, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_16)
        self.label_26.setObjectName("label_26")
        self.gridLayout_11.addWidget(self.label_26, 1, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_16)
        self.label_27.setObjectName("label_27")
        self.gridLayout_11.addWidget(self.label_27, 1, 2, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_16, 3, 0, 1, 2)
        self.groupBox_15 = QtGui.QGroupBox(self.tab_VoIP)
        self.groupBox_15.setObjectName("groupBox_15")
        self.formLayout_5 = QtGui.QFormLayout(self.groupBox_15)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_23 = QtGui.QLabel(self.groupBox_15)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_23)
        self.VoIP_delay = QtGui.QSpinBox(self.groupBox_15)
        self.VoIP_delay.setSuffix("")
        self.VoIP_delay.setMaximum(5000)
        self.VoIP_delay.setSingleStep(10)
        self.VoIP_delay.setProperty("value", 20)
        self.VoIP_delay.setObjectName("VoIP_delay")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.VoIP_delay)
        self.radioButton = QtGui.QRadioButton(self.groupBox_15)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.SpanningRole, self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox_15)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.SpanningRole, self.radioButton_2)
        self.gridLayout_8.addWidget(self.groupBox_15, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_VoIP, "")
        self.tab_Mail = QtGui.QWidget()
        self.tab_Mail.setObjectName("tab_Mail")
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_Mail)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.widget = QtGui.QWidget(self.tab_Mail)
        self.widget.setObjectName("widget")
        self.gridLayout_10.addWidget(self.widget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_Mail, "")
        self.tab_DNS = QtGui.QWidget()
        self.tab_DNS.setObjectName("tab_DNS")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_DNS)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget_6 = QtGui.QWidget(self.tab_DNS)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_7.addWidget(self.widget_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_DNS, "")
        self.tab_HTTP = QtGui.QWidget()
        self.tab_HTTP.setObjectName("tab_HTTP")
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_HTTP)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.widget_8 = QtGui.QWidget(self.tab_HTTP)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_9.addWidget(self.widget_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_HTTP, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 558, 19))
        self.menuBar.setObjectName("menuBar")
        self.menuHallo = QtGui.QMenu(self.menuBar)
        self.menuHallo.setObjectName("menuHallo")
        self.menuInfo = QtGui.QMenu(self.menuBar)
        self.menuInfo.setObjectName("menuInfo")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuHallo.addAction(self.actionExit)
        self.menuBar.addAction(self.menuHallo.menuAction())
        self.menuBar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Picture", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hosts:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h1: running a simple HTTP server</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h2: wireshark</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h2: xterm window to start download (initiate TCP connection)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Link:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- 20ms delay </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- 5% paket loss</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Sender queue length</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Instructions", None, QtGui.QApplication.UnicodeUTF8))
        self.TCPloss_Step1.setText(QtGui.QApplication.translate("MainWindow", "Start setup", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("MainWindow", "wget -O /dev/null 10.0.0.1/smallfile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Step 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.TCPloss_Exit.setText(QtGui.QApplication.translate("MainWindow", "Stop demo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Step 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.TCPloss_Step2.setText(QtGui.QApplication.translate("MainWindow", "Start download", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Step 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "This command will be executed:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Link delay: (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Paket loss: (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Queue length (sender):", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_TCP), QtGui.QApplication.translate("MainWindow", "TCP packet loss", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_2.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hosts:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h1: running a DHCP daemon</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h2: wireshark</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h2: xterm window to request an IP address via dhclient</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Link:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- 20ms delay </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Link delay: (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.DHCP_daemon_leases.setText(QtGui.QApplication.translate("MainWindow", "Use new server lease file", None, QtGui.QApplication.UnicodeUTF8))
        self.DHCP_client_leases.setText(QtGui.QApplication.translate("MainWindow", "Use new client lease file", None, QtGui.QApplication.UnicodeUTF8))
        self.DHCP_random_MAC.setText(QtGui.QApplication.translate("MainWindow", "Use random MAC addresses", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Picture", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Instructions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Step 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.DHCP_Step1.setText(QtGui.QApplication.translate("MainWindow", "Start setup", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setText(QtGui.QApplication.translate("MainWindow", "dhclient -d -v -lf /var/lib/dhcp/dhclient.leases.mn h2-eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Step 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.DHCP_Exit.setText(QtGui.QApplication.translate("MainWindow", "Stop demo", None, QtGui.QApplication.UnicodeUTF8))
        self.DHCP_Step2.setText(QtGui.QApplication.translate("MainWindow", "Execute dhclient", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Step 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "This command wil be executed:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DHCP), QtGui.QApplication.translate("MainWindow", "DHCP", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("MainWindow", "Picture", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_3.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hosts:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h1: running a FTP daemon</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h2: wireshark</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h2: xterm window to request a file from FTP server</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Link:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- 20ms delay</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("MainWindow", "Instructions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Step 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.FTP_Step1.setText(QtGui.QApplication.translate("MainWindow", "Start setup", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_3.setText(QtGui.QApplication.translate("MainWindow", "python ftpclient.py -s 10.0.0.1 -p 21 -u mininet -pw mininet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Step 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.FTP_Exit.setText(QtGui.QApplication.translate("MainWindow", "Stop demo", None, QtGui.QApplication.UnicodeUTF8))
        self.FTP_Step2.setText(QtGui.QApplication.translate("MainWindow", "Start file download", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Step 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "This command wil be executed:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Link delay: (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.FTP_pasv.setText(QtGui.QApplication.translate("MainWindow", "Verwende \"passive mode\" (statt \"active mode\") (FIXME)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_FTP), QtGui.QApplication.translate("MainWindow", "FTP", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_4.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hosts:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h1: running asterisk daemon</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h1: wireshark</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h2: Softphone linphone</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h3: Softphone ekiga</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Link:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- 20ms delay</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_14.setTitle(QtGui.QApplication.translate("MainWindow", "Picture", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_16.setTitle(QtGui.QApplication.translate("MainWindow", "Instructions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Step 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.VoIP_Step1.setText(QtGui.QApplication.translate("MainWindow", "Start setup", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_4.setText(QtGui.QApplication.translate("MainWindow", "\"ekiga\" and \"linphone\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Step 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.VoIP_Exit.setText(QtGui.QApplication.translate("MainWindow", "Stop demo", None, QtGui.QApplication.UnicodeUTF8))
        self.VoIP_Step2.setText(QtGui.QApplication.translate("MainWindow", "Start softphones", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Step 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "These commands wil be executed:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_15.setTitle(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Link delay: (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "Use asterisk as registrar for softphones", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "Don\'t use asterisk as registrar (only direct connect is possible)  (FIXME)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_VoIP), QtGui.QApplication.translate("MainWindow", "VoIP", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Mail), QtGui.QApplication.translate("MainWindow", "Mail", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_DNS), QtGui.QApplication.translate("MainWindow", "DNS", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_HTTP), QtGui.QApplication.translate("MainWindow", "HTTP", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHallo.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInfo.setTitle(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

