# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed May 27 01:32:57 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(574, 561)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 551, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 180, 251, 111))
        self.groupBox.setObjectName("groupBox")
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 141, 21))
        self.label_9.setObjectName("label_9")
        self.TCPloss_delay = QtGui.QSpinBox(self.groupBox)
        self.TCPloss_delay.setGeometry(QtCore.QRect(170, 20, 61, 21))
        self.TCPloss_delay.setSuffix("")
        self.TCPloss_delay.setMaximum(5000)
        self.TCPloss_delay.setSingleStep(10)
        self.TCPloss_delay.setProperty("value", 20)
        self.TCPloss_delay.setObjectName("TCPloss_delay")
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.label_10.setObjectName("label_10")
        self.TCPloss_loss = QtGui.QSpinBox(self.groupBox)
        self.TCPloss_loss.setGeometry(QtCore.QRect(170, 50, 61, 21))
        self.TCPloss_loss.setSuffix("")
        self.TCPloss_loss.setPrefix("")
        self.TCPloss_loss.setMaximum(100)
        self.TCPloss_loss.setProperty("value", 5)
        self.TCPloss_loss.setObjectName("TCPloss_loss")
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 80, 141, 21))
        self.label_11.setObjectName("label_11")
        self.TCPloss_swin = QtGui.QSpinBox(self.groupBox)
        self.TCPloss_swin.setGeometry(QtCore.QRect(170, 80, 61, 22))
        self.TCPloss_swin.setMinimum(1)
        self.TCPloss_swin.setProperty("value", 3)
        self.TCPloss_swin.setObjectName("TCPloss_swin")
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 300, 511, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 52, 23))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.TCPloss_Step1 = QtGui.QPushButton(self.groupBox_2)
        self.TCPloss_Step1.setGeometry(QtCore.QRect(80, 20, 90, 23))
        self.TCPloss_Step1.setObjectName("TCPloss_Step1")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 52, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(210, 50, 281, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(210, 70, 281, 22))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.lineEdit.setFont(font)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(20, 100, 52, 16))
        self.label_12.setObjectName("label_12")
        self.TCPloss_Step2 = QtGui.QPushButton(self.groupBox_2)
        self.TCPloss_Step2.setGeometry(QtCore.QRect(80, 50, 111, 24))
        self.TCPloss_Step2.setObjectName("TCPloss_Step2")
        self.TCPloss_Exit = QtGui.QPushButton(self.groupBox_2)
        self.TCPloss_Exit.setGeometry(QtCore.QRect(80, 100, 77, 24))
        self.TCPloss_Exit.setObjectName("TCPloss_Exit")
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 251, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.textEdit = QtGui.QTextEdit(self.groupBox_3)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 231, 141))
        self.textEdit.setObjectName("textEdit")
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(270, 0, 251, 211))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 231, 181))
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("TCPlost.png"))
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 0, 251, 171))
        self.groupBox_5.setObjectName("groupBox_5")
        self.textEdit_2 = QtGui.QTextEdit(self.groupBox_5)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 20, 231, 141))
        self.textEdit_2.setObjectName("textEdit_2")
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(270, 0, 251, 211))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_8 = QtGui.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 231, 181))
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("TCPlost.png"))
        self.label_8.setObjectName("label_8")
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 180, 251, 141))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_14 = QtGui.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.label_14.setObjectName("label_14")
        self.DHCP_delay = QtGui.QSpinBox(self.groupBox_7)
        self.DHCP_delay.setGeometry(QtCore.QRect(170, 20, 61, 21))
        self.DHCP_delay.setSuffix("")
        self.DHCP_delay.setMaximum(5000)
        self.DHCP_delay.setSingleStep(10)
        self.DHCP_delay.setProperty("value", 20)
        self.DHCP_delay.setObjectName("DHCP_delay")
        self.DHCP_daemon_leases = QtGui.QCheckBox(self.groupBox_7)
        self.DHCP_daemon_leases.setGeometry(QtCore.QRect(10, 50, 191, 19))
        self.DHCP_daemon_leases.setChecked(True)
        self.DHCP_daemon_leases.setTristate(False)
        self.DHCP_daemon_leases.setObjectName("DHCP_daemon_leases")
        self.DHCP_client_leases = QtGui.QCheckBox(self.groupBox_7)
        self.DHCP_client_leases.setGeometry(QtCore.QRect(10, 80, 191, 19))
        self.DHCP_client_leases.setChecked(True)
        self.DHCP_client_leases.setObjectName("DHCP_client_leases")
        self.DHCP_random_MAC = QtGui.QCheckBox(self.groupBox_7)
        self.DHCP_random_MAC.setGeometry(QtCore.QRect(10, 110, 201, 19))
        self.DHCP_random_MAC.setChecked(False)
        self.DHCP_random_MAC.setObjectName("DHCP_random_MAC")
        self.groupBox_8 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 330, 521, 131))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_5 = QtGui.QLabel(self.groupBox_8)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 52, 23))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setObjectName("label_5")
        self.DHCP_Step1 = QtGui.QPushButton(self.groupBox_8)
        self.DHCP_Step1.setGeometry(QtCore.QRect(80, 20, 90, 23))
        self.DHCP_Step1.setObjectName("DHCP_Step1")
        self.label_6 = QtGui.QLabel(self.groupBox_8)
        self.label_6.setGeometry(QtCore.QRect(20, 50, 52, 16))
        self.label_6.setObjectName("label_6")
        self.label_17 = QtGui.QLabel(self.groupBox_8)
        self.label_17.setGeometry(QtCore.QRect(220, 50, 281, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 70, 291, 22))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_19 = QtGui.QLabel(self.groupBox_8)
        self.label_19.setGeometry(QtCore.QRect(20, 100, 52, 16))
        self.label_19.setObjectName("label_19")
        self.DHCP_Step2 = QtGui.QPushButton(self.groupBox_8)
        self.DHCP_Step2.setGeometry(QtCore.QRect(80, 50, 111, 24))
        self.DHCP_Step2.setObjectName("DHCP_Step2")
        self.DHCP_Exit = QtGui.QPushButton(self.groupBox_8)
        self.DHCP_Exit.setGeometry(QtCore.QRect(80, 100, 77, 24))
        self.DHCP_Exit.setObjectName("DHCP_Exit")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 574, 19))
        self.menuBar.setObjectName("menuBar")
        self.menuHallo = QtGui.QMenu(self.menuBar)
        self.menuHallo.setObjectName("menuHallo")
        self.menuInfo = QtGui.QMenu(self.menuBar)
        self.menuInfo.setObjectName("menuInfo")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuHallo.addAction(self.actionExit)
        self.menuBar.addAction(self.menuHallo.menuAction())
        self.menuBar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Link delay: (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Paket loss: (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Queue length: (sender)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Instructions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Step 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.TCPloss_Step1.setText(QtGui.QApplication.translate("MainWindow", "Start setup", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Step 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "This command will be executed:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("MainWindow", "wget -O /dev/null 10.0.0.1/smallfile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Step 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.TCPloss_Step2.setText(QtGui.QApplication.translate("MainWindow", "Start download", None, QtGui.QApplication.UnicodeUTF8))
        self.TCPloss_Exit.setText(QtGui.QApplication.translate("MainWindow", "Stop demo", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hosts:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h1: running a simple HTTP server</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h2: wireshark</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h2: xterm window to start download (initiate TCP connection)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Link:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- 20ms delay </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- 5% paket loss</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Sender queue length</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Picture", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "TCP packet loss", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_2.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hosts:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h1: running a DHCP daemon</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h2: wireshark</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">h2: xterm window to request an IP address via dhclient</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Link:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- 20ms delay </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Picture", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Link delay: (ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.DHCP_daemon_leases.setText(QtGui.QApplication.translate("MainWindow", "Use new server lease file", None, QtGui.QApplication.UnicodeUTF8))
        self.DHCP_client_leases.setText(QtGui.QApplication.translate("MainWindow", "Use new client lease file", None, QtGui.QApplication.UnicodeUTF8))
        self.DHCP_random_MAC.setText(QtGui.QApplication.translate("MainWindow", "Use random MAC addresses", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Instructions", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Step 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.DHCP_Step1.setText(QtGui.QApplication.translate("MainWindow", "Start setup", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Step 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "This command wil be executed:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setText(QtGui.QApplication.translate("MainWindow", "dhclient -d -v -lf /var/lib/dhcp/dhclient.leases.mn h2-eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Step 3:", None, QtGui.QApplication.UnicodeUTF8))
        self.DHCP_Step2.setText(QtGui.QApplication.translate("MainWindow", "Execute dhclient", None, QtGui.QApplication.UnicodeUTF8))
        self.DHCP_Exit.setText(QtGui.QApplication.translate("MainWindow", "Stop demo", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "DHCP", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "ARP", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "NAT", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "BGP", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHallo.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuInfo.setTitle(QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

