#!/bin/sh

memmin=4096

sudo sysctl -w net.ipv4.tcp_wmem="$memmin $memmin $memmin"
sudo sysctl -w net.ipv4.tcp_rmem="$memmin $memmin $memmin"

sudo sysctl -w net.core.rmem_default=$memmin
sudo sysctl -w net.core.rmem_max=$memmin
sudo sysctl -w net.core.wmem_default=$memmin
sudo sysctl -w net.core.wmem_max=$memmin

