#!/bin/sh
sudo sysctl -w net.ipv4.tcp_wmem="10240 87380 16777216"
sudo sysctl -w net.ipv4.tcp_rmem="10240 87380 16777216"

sudo sysctl -w net.core.rmem_default=212992
sudo sysctl -w net.core.rmem_max=16777216
sudo sysctl -w net.core.wmem_default=212992
sudo sysctl -w net.core.wmem_max=16777216


